BUG: do not access global vars while in `__del__`
The method `dd.bdd.BDD.__del__` calls the method
`dd.bdd.BDD.collect_garbage`. The method
`collect_garbage` accesses the global variable
`logger`. By the time that `BDD.__del__` is
called, the variable `logger` may not be present
any more, because the Python interpreter is
shutting down.

This bug was noticed when an exception was
raised during testing (the dots resulted from
editing the paths that appeared in the traceback):

```
Exception ignored in: <bound method BDD.__del__ of <dd.bdd.BDD object at
0x7f4da6ba5a90>>
Traceback (most recent call last):
  File
"/.../Python/3.6.14/x64/lib/python3.6/site-packages/dd/bdd.py",
line 185, in __del__
  File
"/.../Python/3.6.14/x64/lib/python3.6/site-packages/dd/bdd.py",
line 847, in collect_garbage
AttributeError: 'NoneType' object has no attribute 'debug'
```

This error has not been observed on Python > 3.6.